-- set that database as active
use irctcproject;

-- stations table
create table stations(
station_id varchar(10) primary key,
station_name varchar(50)
);


-- insert values into stations table

insert into stations values('YPR','YESVANTPUR JN');
insert into stations values('BAW','CHIK BANAVAR');
insert into stations values('KIAT','KYATSANDRA');
insert into stations values('TK','TUMKUR');
insert into stations values('GBB','GUBBI');
insert into stations values('TTR','TIPTUR');
insert into stations values('ASK','ARSIKERE JN');
insert into stations values('DRU','KADUR');
insert into stations values('RRB','BIRUR JN');
insert into stations values('AJP','AJJAMPUR');
insert into stations values('SHV','SHIVANI');
insert into stations values('HSD','HOSDURGA ROAD');
insert into stations values('RGI','RAMGIRI');
insert into stations values('HLK','HOLALKERE');
insert into stations values('JRU','CHIKJAJUR JN');
insert into stations values('CTA','CHITRADURG');
insert into stations values('BAHI','BALLENAHALLI');
insert into stations values('CHKE','CHALLAKERE');
insert into stations values('MOMU','MOLAKALMURU');
insert into stations values('RDG','RAYADURG');
insert into stations values('SLM','SOMALAPURAM');
insert into stations values('OBM','OBALAPURAM');
insert into stations values('BAY','BELLARY JN');
insert into stations values('KDN','KUDATINI');
insert into stations values('DAJ','DAROJI');
insert into stations values('TNGL','TORANAGALLU');
insert into stations values('GNR','GADIGANURU');
insert into stations values('HPT','HOSPET JN');
insert into stations values('MRB','MUNIRABAD');
insert into stations values('GIN','GINIGERA');
insert into stations values('BDGU','BUDHAGUMPA');
insert into stations values('JBGD','JABBALGUDDA');
insert into stations values('CKBK','CHIKKABENAKAL');
insert into stations values('GGVT','GANGAVATHI');
insert into stations values('SRNM','SRIRAMANAGAR GRAMA HALT');
insert into stations values('SIDG','SIDDAPUR');
insert into stations values('KTGG','KARATAGI');
insert into stations values('DVG','DAVANGERE');
insert into stations values('HVR','HAVERI');
insert into stations values('UBL','HUBLI JN');
insert into stations values('GDG','GADAG JN');
insert into stations values('KBL','KOPPAL');
insert into stations values('GTL','GUNTAKAL JN');
insert into stations values('KRNT','KURNOOL TOWN');
insert into stations values('KCG','KACHEGUDA');
insert into stations values('BPQ','BALHARSHAH');
insert into stations values('NGP','NAGPUR');
insert into stations values('BPL','BHOPAL JN');
insert into stations values('VGLB','VEERANGANA LAXMIBAI JN');
insert into stations values('GWL','GWALIOR JN');
insert into stations values('NZM','DELHI HAZRAT NIZAMUDDIN');
insert into stations values('MYS','MYSORE JN');
insert into stations values('PANP','PANDAVAPURA');
insert into stations values('MYA','MANDYA');
insert into stations values('MAD','MADDUR');
insert into stations values('CPT','CHANNAPATNA');
insert into stations values('RMGM','RAMANAGARAM');
insert into stations values('BID','BIDADI');
insert into stations values('KGI','KENGERI');
insert into stations values('SBC','BANGALORE CITY JN');
insert into stations values('YNK','YELHANKA JN');
insert into stations values('DBU','DODBALLAPUR');
insert into stations values('GBD','GAURIBIDANUR');
insert into stations values('HUP','HINDUPUR');
insert into stations values('PKD','PENUKONDA');
insert into stations values('DMM','DHARMAVARAM JN');
insert into stations values('BNP','BHANAPUR');
insert into stations values('NGR','ANNIGERI');
insert into stations values('SSPN','SATYA SAI P NILAYAM');
insert into stations values('RC','RAICHUR');
insert into stations values('SEM','SERAM');
insert into stations values('SC','SECUNDERABAD JN');
insert into stations values('KZJ','KAZIPET JN');
insert into stations values('ET','ITARSI JN');
insert into stations values('AGC','AGRA CANTT');
insert into stations values('MAS','MGR CHENNAI CENTRAL');
insert into stations values('KPD','KATPADI JN');
insert into stations values('BDM','BADAMI');
insert into stations values('BGK','BAGALKOT');
insert into stations values('BJP','VIJAYAPURA');
insert into stations values('SUR','SOLAPUR JN');
insert into stations values('KWV','KURDUVADI');
insert into stations values('SNSI','SAINAGAR SHIRDI');
insert into stations values('BNC','BANGALORE CANT');
insert into stations values('ATP','ANANTAPUR');
insert into stations values('AD','ADONI');
insert into stations values('MALM','MANTHRALAYAM RD');
insert into stations values('YG','YADGIR');
insert into stations values('WADI','WADI');
insert into stations values('KLBG','KALABURAGI JUNCTION');
insert into stations values('DD','DAUND JN');
insert into stations values('ANG','AHMADNAGAR');
insert into stations values('BAP','BELAPUR');
insert into stations values('KPG','KOPARGAON');
insert into stations values('MMR','MANMAD JN');
insert into stations values('JL','JALGAON JN');
insert into stations values('BSL','BHUSAVAL JN');
insert into stations values('BAU','BURHANPUR');
insert into stations values('KNW','KHANDWA');
insert into stations values('BINA','BINA JN');
insert into stations values('MTJ','MATHURA JN');
insert into stations values('NDLS','NEW DELHI');
insert into stations values('SMVB','SMVT BENGALURU');
insert into stations values('KJM','KRISHNARAJAPURAM');
insert into stations values('BWT','BANGARAPET');
insert into stations values('KPN','KUPPAM');
insert into stations values('JTJ','JOLARPETTAI');
insert into stations values('TPTY','TIRUPATI MAIN');
insert into stations values('RU','RENIGUNTA JN');
insert into stations values('GDR','GUDUR JN');
insert into stations values('NLR','NELLORE');
insert into stations values('OGL','ONGOLE');
insert into stations values('CLX','CHIRALA');
insert into stations values('BPP','BAPATLA');
insert into stations values('TEL','TENALI JN');
insert into stations values('BZA','VIJAYAWADA JN');
insert into stations values('EE','ELURU');
insert into stations values('TDD','TADEPALLIGUDEM');
insert into stations values('RJY','RAJAMUNDRY');
insert into stations values('SLO','SAMALKOT JN');
insert into stations values('VSKP','VISAKHAPATNAM');
insert into stations values('VZM','VIZIANAGRAM JN');
insert into stations values('CHE','SRIKAKULAM ROAD');
insert into stations values('PSA','PALASA');
insert into stations values('BAM','BRAHMAPUR');
insert into stations values('BALU','BALUGAON');
insert into stations values('KUR','KHURDA ROAD JN');
insert into stations values('BBS','BHUBANESWAR');
insert into stations values('CTC','CUTTACK');
insert into stations values('JJKR','JAJPUR KEONJHAR ROAD');
insert into stations values('BHC','BHADRAKH');
insert into stations values('BLS','BALASORE');
insert into stations values('KGP','KHARAGPUR JN');
insert into stations values('MCA','MECHEDA');
insert into stations values('SRC','SANTRAGACHI JN');
insert into stations values('HWH','HOWRAH JN');
insert into stations values('VN','VANIYAMBADI');
insert into stations values('AB','AMBUR');
insert into stations values('AJJ','ARAKKONAM');
insert into stations values('PER','PERAMBUR');
insert into stations values('RNR','RANIBENNUR');
insert into stations values('PUNE','PUNE JN');
insert into stations values('KYN','KALYAN JN');
insert into stations values('BSR','VASAI ROAD');
insert into stations values('BOR','BOISAR');
insert into stations values('VAPI','VAPI');
insert into stations values('ST','SURAT');
insert into stations values('AKV','ANKLESHWAR JN');
insert into stations values('BRC','VADODARA JN');
insert into stations values('ANND','ANAND JN');
insert into stations values('ND','NADIAD JN');
insert into stations values('ADI','AHMEDABAD JN');
insert into stations values('MSH','MAHESANA JN');
insert into stations values('PNU','PALANPUR JN');
insert into stations values('ABR','ABU ROAD');
insert into stations values('FA','FALNA');
insert into stations values('RANI','RANI');
insert into stations values('MJ','MARWAR JN');
insert into stations values('PMY','PALI MARWAR');
insert into stations values('JU','JODHPUR JN');
insert into stations values('MTD','MERTA ROAD JN');
insert into stations values('NGO','NAGAUR');
insert into stations values('NOK','NOKHA');
insert into stations values('BKN','BIKANER JN');
insert into stations values('KSN','KRISHNA');
insert into stations values('SADP','SAIDAPUR');
insert into stations values('NW','NALWAR');
insert into stations values('SDB','SHAHABAD');
insert into stations values('GUR','GANAGAPUR ROAD');
insert into stations values('DUD','DUDHANI');
insert into stations values('AKOR','AKALKOT ROAD');
insert into stations values('LNL','LONAVALA');
insert into stations values('DR','MUMBAI DADAR CENTRAL');
insert into stations values('URI','URULI');
insert into stations values('CSMT','MUMBAI CSMT');

truncate table stations;

-- retreive stations details
select * from stations;